#!/bin/bash

function get_id
{
    filename=$(basename $1)
    if [[ -f $1 && $filename =~ [1-todo|2-doing|3-done]-[0-9]*- ]]
    then
        echo $filename | cut -d"-" -f3
    else
        return 1
    fi
}

function get_cellname
{
    echo "$(get_id $1) $(get_title $1)"
}
