#!/bin/bash

cmd=$1
export KANBASH_DIR=$HOME/projects/kanbash
export KANBASH_TASK_DIR=$KANBASH_DIR/tasks/

case $cmd in
    ls)
        kanbash-ls
        ;;
    *)
        >&2 echo "Not a valid kanbash command: $cmd"
        exit 1
        ;;
esac
