#!/bin/bash

cmd=$1
export KANBASH_TASK_DIR="../tasks/"

case $cmd in
    ls)
        ./kanbash-ls
        ;;
    "title")
        ./kanbash-title $2
        ;;
    *)
        >&2 echo "Not a valid kanbash command: $cmd"
        exit 1
        ;;
esac
