#!/bin/bash

# causes array to be empty when there are no matches
shopt -s nullglob

todo=(${KANBASH_TASK_DIR}1-todo*)
doing=(${KANBASH_TASK_DIR}2-doing*)
done=(${KANBASH_TASK_DIR}3-done*)

counts=$(printf "%s\n" ${#todo[@]} ${#doing[@]} ${#done[@]})
num_rows=$(echo "$counts" | sort -n | tail -n1)

table="${KANBASH_TASK_DIR}.table"
echo "TODO,DOING,DONE" > $table

for i in $(seq 0 $num_rows)
do
    echo "$(kanbash title ${todo[i]}),$(kanbash title ${doing[i]}),$(kanbash title ${done[i]})" >> $table
done

column -t -s ',' $table
