#!/bin/bash

# causes array to be empty when there are no matches
shopt -s nullglob

todo=(${KANBASH_TASK_DIR}/1-todo*)
doing=(${KANBASH_TASK_DIR}/2-doing*)
done=(${KANBASH_TASK_DIR}/3-done*)

echo ${#todo[@]}
echo ${#doing[@]}
echo ${#done[@]}
