#!/bin/bash

source $KANBASH_DIR/src/kanbash-utils

# causes array to be empty when there are no matches
shopt -s nullglob

todo=(${KANBASH_TASK_DIR}1-todo*)
doing=(${KANBASH_TASK_DIR}2-doing*)
done=(${KANBASH_TASK_DIR}3-done*)

counts=$(printf "%s\n" ${#todo[@]} ${#doing[@]} ${#done[@]})
num_rows=$(echo "$counts" | sort -n | tail -n1)

table="${KANBASH_TASK_DIR}.table"
echo "01 TODO,02 DOING,03 DONE" > $table
printf '\n' >> $table

for (( i=0; i<$num_rows; i++ ))
do
    todotask="$(get_cellname ${todo[i]})"
    doingtask="$(get_cellname ${doing[i]})"
    donetask="$(get_cellname ${done[i]})"

    echo "$todotask,$doingtask,$donetask" >> $table
done

column -tL -s ',' -o '          ' $table
